### ISSUE TITLE
صف دانلود

### ISSUE THREAD

**Issue by salam-mahdinasiri** [NabiKAZ/namava-downloader#10]
امکان قراردادن چند تا فایل برای دانلود
مثل idm
و مشخص کردن محل ذخیره فایل دانلود شده
رو هم لطفا اضافه کنید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

باتشکر از پیشنهادات شما.

برای دانلود همزمان چند فیلم، فقط کافیست برنامه را چند بار اجرا کنید. یعنی وقتی دستور دانلود اولین فیلم داده می‎شود و به خط فرمان باز می‎گردید، کافیست دوباره برنامه را اجرا و فیلم بعدی را دانلود کنید. توجه داشته باشید که در این حالت، توسط فایل نمایش وضعیت (`stats.php`) می‎توانید وضعیت پیشرفت تمام فیلم‎های در حال دانلود را یکجا مشاهده کنید.

درمورد مشخص کردن محل ذخیره فایل دانلود، تنها کافیست در فایل `download.php` متغییر [`‎$base_path`](https://github.com/NabiKAZ/namava-downloader/blob/master/download.php#L9) را ویرایش و مسیر مورد نظر خود را در آن قرار دهید.
همچنین برای گزارشگیری، فایل `stats.php` متغییر [`‎$base_path`](https://github.com/NabiKAZ/namava-downloader/blob/master/stats.php#L128)
<div dir=ltr>

```
$base_path = 'download/';
```

**Comment by salam-mahdinasiri** [comment]
منظورم این بود که در صف قرار بگیرند
نه اینکه باهم دانلود بشن

**Comment by NabiKAZ** [comment]
<div dir=rtl>

برای این منظور، کارهای زیادی میشه کرد؛ ولی راهی که الان به ذهنم میرسه اینطوریه:

قبل از هر چیز مطمئن بشید که با اسکریپت لاگین هستید.

اول از همه در فایل `download.php` قبل از خط [`if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {`](https://github.com/NabiKAZ/namava-downloader/blob/master/download.php#L130) این رو بنویسید:
</div>
<div dir=ltr>

```
shell_exec($cmd);die;
```
</div>
<div dir=rtl>

با اینکار، اسکریپت تا دانلود کامل فیلم منتظر میمونه. (البته دیگر گزارش پیشرفت کار توسط فایل stats.php از کار میافته)

بعدش یک سری فایل تکست با اسم عددی درست کنید و خط اول اسم آیدی ویدیو و خط دوم شماره کیفیت مد نظر رو وارد کنید. برای مثال اینطوری:

نام فایل: ‎1.txt
محتوا:
11297
4

نام فایل: ‎2.txt
محتوا:
7558
3

نام فایل: ‎3.txt
محتوا:
11403
1

حالا یه فایل ایجاد کنید به نام `run.bat` و اینها رو توش بنویسید:
</div>
<div dir=ltr>

```
@ECHO OFF
SET number=3
FOR /L %%n IN (1,1,%number%) DO (
  php download.php < %%n.txt
)
```
</div>
<div dir=rtl>

(بجای عدد 3 تعداد فایلهای مربوط به ویدیوها رو بنویسید)

خب کار تمونه و فقط در خط فرمان بنویسید:
</div>
<div dir=ltr>

```
run
```
</div>
<div dir=rtl>

تک تک و پشت سرهم فیلمها با کیفیتی که تعریف کردید دانلود میشن.

من چون الان اکانت نماوا ندارم، نتونستم دقیق تست کنم ولی برای فیلیمو کار میکنه، لطفاً تست کنید و اگر مشکلی بود در همینجا اعلام کنید.

**Comment by salam-mahdinasiri** [comment]
این کد مگه برای فیلیمو هم کار می‌کنه؟
