### ISSUE TITLE
حروف فارسی درست نمایش داده نمیشن

### ISSUE THREAD

**Issue by salam-mahdinasiri** [NabiKAZ/namava-downloader#11]
![download](https://user-images.githubusercontent.com/9952616/47956247-c2338b80-dfb6-11e8-919d-709e5d817260.jpg)

**Comment by NabiKAZ** [comment]
<div dir=rtl>

بله من قبلاً به این مشکل برخورد کردم، متاسفانه این مشکل فقط در ویندوز وجود داره و در لینوکس مشکلی نداره و البته مشکل از سمت کد های PHP نیست چرا که حتی اگر dir بزنید، فایلهای فارسی رو درست نشون نمیده.

و قبلاً خیلی سرچ کردم به نتیجه دقیقی نرسیدم. شما هم اگر در گوگل سرچ کنید میبینید که مشکل خیلی هاست.

اما به عنوان یک راه حل ناقص:
وارد Properties پنجره cmd بشید، فونت رو روی Courier New بگذارید.
فونت فارسی درست میشه ولی حروف از هم جدا هستند و باید از چپ به راست بخونید!


![image](https://user-images.githubusercontent.com/246721/47958808-6f72c780-dfe8-11e8-98c4-633662424bc4.png)

**Comment by Hamid-Najafi** [comment]
برای ویندوز از این استفاده کنید

https://cmder.net

**Comment by NabiKAZ** [comment]
<div dir=rtl>

همچنین با استفاده از برنامه [Git Bash](https://git-scm.com/downloads) که شبیه ساز پوسته لینوکس است و همراه Git که اکثراً برنامه نویسان نصب دارن، نصب میشه هم تا حدود زیادی مشکل حل میشه.

![image](https://user-images.githubusercontent.com/246721/118409232-9a046780-b69e-11eb-9cbf-f82f973b0b3e.png)

**Comment by ABMNTM** [comment]
`int main()
{
}
`
