### ISSUE TITLE
این کد برای فیلیمو هم کار می‌کنه؟

### ISSUE THREAD

**Issue by salam-mahdinasiri** [NabiKAZ/namava-downloader#12]
_Originally posted by @mahdi-alavi in https://github.com/NabiKAZ/namava-downloader/issues/10#issuecomment-435667519_

**Comment by NabiKAZ** [comment]
<div dir=rtl>

بله برای فیلیمو اینجاست:
https://github.com/NabiKAZ/filimo-downloader
و اون توضیحات برای دانلود پشت سرهم برای فیلیمو هم کار میکنه.
