### ISSUE TITLE
کار با سورس برنامه

### ISSUE THREAD

**Issue by Adexl** [NabiKAZ/namava-downloader#13]
سورس نماوا رو دقیقا باید کجا وارد یا نصب کنیم؟؟؟
لطفا سریع جواب بدین

**Comment by NabiKAZ** [comment]
<div dir=rtl>

لطفاً راهنمای استفاده را مطالعه کنید:

https://github.com/NabiKAZ/namava-downloader#%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87

همچنین نیازمندی های پروژه:

https://github.com/NabiKAZ/namava-downloader#%D9%86%DB%8C%D8%A7%D8%B2%D9%85%D9%86%D8%AF%DB%8C%D9%87%D8%A7

**Comment by NabiKAZ** [comment]
<div dir=rtl>

> خب من همه چیزارو نصب کردم فقط وقتی php download.php رو میزنم میگه نمیشه بازش کرد

منظورتون از اینکه "میگه نمیشه بازش کرد" چیه؟ لطفاً اصل پیغام خطا را بگذارید.

**Comment by Adexl** [comment]
Cloudnt cant open download.php

**Comment by NabiKAZ** [comment]
<div dir=rtl>

شما در مسیر فایل download.php نیستید. با دستور cd وارد مسیر برنامه شوید.

**Comment by Adexl** [comment]
میتونم از طریق تلگرام با شما در ارتباط باشم؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

بله مشکلی نیست دوست من @NabiKAZ 

ولی ترجیحاً و لطفاً موضوع را همینجا پیگیری کنید چراکه ممکن است مشکل شما، مشکل دیگران نیز باشد و این گفتگو به آنها نیز کمک کند.

**Comment by Adexl** [comment]
الان download.php رو کجا بریزم؟

**Comment by Adexl** [comment]
الان به صورت "پی اچ پی ادرس فایل" دستور دادم این ارورو داد

C:\Users\Adel>php C:\Users\Adel\Desktop\namava-downloader-master\download.php
Namava Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: https://www.namava.ir/
Project link: https://github.com/NabiKAZ/namava-downloader
===========================================================
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in C:\Users\Adel\Desktop\namava-downloader-master\download.php:151
Stack trace:
#0 C:\Users\Adel\Desktop\namava-downloader-master\download.php(14): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\Users\Adel\Desktop\namava-downloader-master\download.php on line 151

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Adel\Desktop\namava-downloader-master\download.php:151
Stack trace:
#0 C:\Users\Adel\Desktop\namava-downloader-master\download.php(14): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\Users\Adel\Desktop\namava-downloader-master\download.php on line 151

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فرقی نمیکنه فایلها کجا باشند. مهم اینه که شما در مسیر برنامه باشید و دستورات را وارد کنید.

برای مثال همه فایلهای پروژه رو در مسیر c:\namava کپی کنید و دستور زیر را وارد کنید:
```
cd /d c:\namava
```
بدین ترتیب در مسیر برنامه قرار میگیرید و دستورات php قابل اجرا خواهند بود.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

درمورد مشکل دوم و خطای `Error: Call to undefined function curl_init()` نیز:

شما باید ماژول CURL رو روی PHP خودتون فعال کنید.

فایل php.ini رو (در مسیری که PHP شما نصب شده است) ویرایش کنید و این خط رو پیدا کنید: `extension=php_curl.dll` و اولش "`;`" رو حذف کنید.

**Comment by siavash4** [comment]
باسلام باتوجه به اینکه مباحث تخصصی است ایاامکان نیست مادانلود کنیم بعد توسط ffmpeg یاwinffتبدیل کنیم
اگر امکان دارد مقداری در مورد کار با winff توضیح دهید 
باسپاس

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@siavash4 
راه اندازی چندان پیچیده نیست ضمن اینکه هدف اول بحث آموزشی پروژه است و خب جامعه مخاطب بیشتر برنامه نویسان هستند تا کاربران عادی، به همین جهت برای راه اندازی یک سری مقدمات انتظار میره یک برنامه نویس حداقل اونها رو بدونه.

winff تنها یک پوسته و لایه گرافیکی برای ffmpeg  هست، اینجا چندان به کار ما نمیاد.

این پروژه توسط ffmpeg  در واقع داره ویدیوی شما رو دانلود میکنه و اصلاً کانورتی انجام نمیده! 😉
