### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Adexl** [NabiKAZ/namava-downloader#14]
خب من همه چیزارو نصب کردم فقط وقتی php download.php رو میزنم میگه نمیشه بازش کرد

و همچنین نمیدونم با سورس نماوا باید چیکار کرد

**Comment by NabiKAZ** [comment]
<div dir=rtl>

لطفاً در همان موضوع [قبلی ](https://github.com/NabiKAZ/namava-downloader/issues/13)بحث را ادامه دهید و موضوع جدید باز نکنید.
