### ISSUE TITLE
آیا از حجم اینترنت ما کم میشود؟

### ISSUE THREAD

**Issue by imani58ir** [NabiKAZ/namava-downloader#15]
سلام...خسته نباشید...من مطلبتونو در مورد سایت نماوا استفاده کردم پیغام دادم هم تشکر کنم هم اینکه  چون دانلود با مبین نت بصورت رایگانه تو سایت نماوا آیا با این روش هم رایگانه میوفته برامون یا چون روش دانلود عادی نیست خللی ایجاد میشه و از اینترنت کم میشه؟...چون من اطلاعاتم تو این کار در حد صفره ممنون میشم راهنمایی بفرمایین...

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون از پیامتون.
دانلودها در واقع شبیه سازی شده‌ی دیدن فیلم هستند! به همین خاطر اگر برای دیدن فیلم نتتون رایگانه، پس برای دانلود هم نباید از حجم کم بشه.
با این حال شما خودتون هم تست کنید و قبل و بعد از دانلود حجمتون رو چک کند و اگر خلاف این بود، در همینجا اطلاع بدید که ما هم بدونیم.

**Comment by imani58ir** [comment]
من تو سایت فیلمیو با video downloadhelper دانلود کردم کم نمیکرد ممکنه اینجا
هم همون جوری باشه؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

بله تکنیک تقریباً مشابه هست و قائدتاً نباید کم کنه.

**Comment by imani58ir** [comment]
ممنون از توضیحاتتون...
