### ISSUE TITLE
عمل نکردن یوزر نیم و پسورد نماوا

### ISSUE THREAD

**Issue by imani58ir** [NabiKAZ/namava-downloader#16]
سلام
سلام...منامروز همچین مشکلی پیدا کردم...یوزر نیم پسورد نماوا رو میزنم وارد نمیشه این ارور میاد

Logging...
PHP Notice: Undefined offset: 1 in C:\Users\namava-downloader-master\namava-downloader-master\download.php on line 27
Logged In.
IMPORTANT: Your private cookies is stored in the 'config/' directory, Be careful about its security!

**Comment by NabiKAZ** [comment]
<div dir=rtl>

تشکر بابت گزارش اشکال.
مشکل حل شد.

**Comment by majid1919** [comment]
سپاس فراوان

**Comment by imani58ir** [comment]
دستتون درد نکنه
