### ISSUE TITLE
چجوری این مشکل رو حل کنم

### ISSUE THREAD

**Issue by DPIDorP** [NabiKAZ/namava-downloader#18]
با سلام
ما هم بچه اهوازیم
تا دستور php رو میزنم این ارور رو میده

Namava Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: https://www.namava.ir/
Project link: https://github.com/NabiKAZ/namava-downloader

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in C:\php\download.php:154
Stack trace:
#0 C:\php\download.php(17): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\php\download.php on line 154

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\php\download.php:154
Stack trace:
#0 C:\php\download.php(17): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\php\download.php on line 154

**Comment by majid1919** [comment]
سلام
احتمالا 
curl 
رو به درستی نصب نکردید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سلام دوست خوب همشهری، 😉 

راه حل مشکل شما رو دقیقاً یکبار اینجا توضیح دادم:
https://github.com/NabiKAZ/namava-downloader/issues/13#issuecomment-439360805
