### ISSUE TITLE
ارور وجود نداشتن آی دی ویدئو

### ISSUE THREAD

**Issue by majid1919** [NabiKAZ/namava-downloader#19]
با سلام و خسته نباشید
هنگام دانلود بعد از وارد کردن ای دی ویدئو با این ارور مواجه میشم

Sorry , not found any video with this ID

البته تا چند روز پیش مشکلی موجود نداشت

ممنون

**Comment by NabiKAZ** [comment]
<div dir=rtl>

یک اصلاحیه انجام دادم. 
لطفاً آپدیت و دوباره تست کنید.

**Comment by majid1919** [comment]
ممنون بابت حل مشکل

دوستانی که از برنامه استفاده می کنید اگر تونستید مبلغی رو کمک کنید
هرچند کوچیک

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@majid1919 
بسیار بسیار متشکرم بابت دونیشن، این باعث انرژی و انگیزه بیشتر میشه و از این بابت ازتون بسیار سپاسگزارم 😉

**Comment by majid1919** [comment]
خواهش می کنم
