### ISSUE TITLE
filimo downloader 

### ISSUE THREAD

**Issue by Soft98AS** [NabiKAZ/namava-downloader#2]
saalam php va ffmpeg chejori nasb konim dash

**Comment by NabiKAZ** [comment]
<div dir=rtl>
ffmpeg رو از اینجا میتونید دانلود کنید:
https://ffmpeg.zeranoe.com/builds/

php رو هم از اینجا میتونید دانلود کنید:
https://windows.php.net/download/

هیچکدوم نیاز به نصب ندارند. تنها از حالت فشرده خارج کنید و مسیر فایل اجرایی اونها که با پسوند .exe مشخص هستند رو در مسیر path قرار بدید.
برای تست، در خط فرمان، یکبار اونها رو اجرا کنید و مطمئن بشید به درستی در دسترس هستند.
