### ISSUE TITLE
فیلم یافت نشد!

### ISSUE THREAD

**Issue by salam-mahdinasiri** [NabiKAZ/namava-downloader#21]
سلام
من هرچه امتحان می‌کنم و آی‌دی های مختلف رو تست می‌کنم
پیام میده
Sorry! Not found any video with this ID.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

من دوباره تست کردم، مشکلی ندیدم و ویدیو پیدا شد.
برای مثال این آیدی ویدیو رو وارد کنید که نیاز به اشتراک هم ندارد: 10731
همچنین قبل از اون مطمئن بشید آخرین نسخه رو دانلود کردید:
https://github.com/NabiKAZ/namava-downloader/archive/master.zip

**Comment by salam-mahdinasiri** [comment]
ممنون
احتمالا چون نسخه‌م به روز نبود، دانلود نمی‌شود
(:
