### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by siavash4** [NabiKAZ/namava-downloader#22]
باسلام وسپاس از پاسخ شما منظورم این بود راهی  برای تبدیل  به منظور اجرا برروی فلش وجوددارد ؟چون تلویزیونم امکان نصب اپ ندارد و برروی لپ تاپ هم امکان تماشای خانوادگی وجود ندارد

**Comment by MASOODOK** [comment]
دوست عزیز شما موفق شدید دانلود کنید ؟ وقتی بشه دانلود کرد و یا از طریق ffmpeg.exe استریمش رو دانلود کرد و ذخیره کرد ( دقیقاً مثل همین ) مشکلی در پخش در دیگر دستگاهها نخواهید داشت
ولی من کلاً موفق نشدم که لاگین کنم با اسکریپت

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@siavash4 

به نظر میرسه مطاب شما در ادامه موضوع دیگری بوده که من اون رو به خاطر ندارم. لطفاً همیشه زیر همون موضوع قبلی پاسخ بدید و اگر مشکل جدیدی بود، یک issue جدید باز کنید. همچنین برای issue خود موضوع مناسب و کامل انتخاب کنید بجای استفاده از عنوان "سوال"!

در نهایت در پاسخ شما، بله شما میتوانید با این اسکریپت فیلم را با فورمت mp4 دانلود و روی فلش کپی و در تلوزیون تماشا کنید. اگر هم تلوزیون فورمت mp4 را پشتیبانی نمیکرد، مبدل های فیلم زیادی در اینترنت وجود دارند که میتوانید استفاده کنید.
