### ISSUE TITLE
پیام خطا پس از اجرا

### ISSUE THREAD

**Issue by MASOODOK** [NabiKAZ/namava-downloader#23]
سلام ممنون از به اشتراک گذاری این اسکریپت امیدوارم که آپدیت بشه و بهبود پیدا کنه من پس از اجرا این پیام خطا رو میگیرم روی خط 154اسکریپت 
لطفاً راهنمایی کنید
با تشکر

`C:\Namava\php73>php download.php
Namava Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: https://www.namava.ir/
Project link: https://github.com/NabiKAZ/namava-downloader

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Namava\php73\download.php:154
Stack trace:
#0 C:\Namava\php73\download.php(17): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\Namava\php73\download.php on line 154`

**Comment by NabiKAZ** [comment]
<div dir=rtl>

راه حل مشکل شما قبلاً در اینجا توضیح داده شده:
https://github.com/NabiKAZ/namava-downloader/issues/13#issuecomment-439360805

**Comment by MASOODOK** [comment]
آقا بسیار ممنون واقعاً عالی بود لذت بردم .. به راحتی دانلود شد ..
در ضمن همیاری منو حتماً خواهید داشت دوست عزیز کار بسیار خوبی انجام دادید ..در یک کلام عالی :
دوستان عزیزی که از این اسکریپت استفاده کردند خواهش میکنم که همیاری رو فراموش نکنید : کارهای ارزشمند باید حمایت بشن .. واقعاً هر چقدر در حد توان حتی شده 1000 تومن خلاصه اینکه خجالت نکشید .. واسه مبالغ کم 
https://zarinp.al/nabikaz

**Comment by NabiKAZ** [comment]
<div dir=rtl>

دوست خوبم MASOODOK،
ممنون از این همه انرژی و همراهی و سپاس بابت دونیشن شما.
فرهنگ دونیشن برای پروژه های غیر تجاری، موجب انرژی و انگیزه است و البته تداوم اون، در من مسئولیتی ایجاد خواهد کرد برای پشتیبانی و ارتقا و رفع باگ های احتمالی در آینده. امیدوارم بتونم به این طریق متقابلاً پاسخ بدم 😉
