### ISSUE TITLE
دانلود نکردن ویدیو

### ISSUE THREAD

**Issue by RaymandSystem** [NabiKAZ/namava-downloader#25]
درود بر شما، سپاس از کار ارزشمندتون، متاسفانه فقط موفق شدم یک ویدیو رو دانلود کنم و بعد از اون هیچ ویدیوی دیگه ای رو نمیتونم دانلود  کنم. تمام مراحل دانلود انجام میشه اما فایل ویدیو دانلود نمیشه. ممنون میشم اگر راهنمایی کنید

**Comment by majid1919** [comment]
سلام 

منم همین مشکل رو دارم . فقط پوستر فیلم دانلود میشه

**Comment by NabiKAZ** [comment]
<div dir=rtl>
بعید نیست که بازم نماوا توی سیستمش تغییراتی داده باشه، الان دسترسیم محدوده، تیکت رو باز میزارم و در اولین فرصت بررسی میکنم.

**Comment by salam-mahdinasiri** [comment]
`[http @ 000001c6f482a300] HTTP error 420 `
`Server returned 4XX Client Error`

**Comment by ghost** [comment]
سلام 
خسته نباشید
دوستان در حال حاضر میشه با این برنامه فیلم های نماوا رو دانلود کرد یا نه؟

**Comment by majid1919** [comment]
سلام تا هفته قبل می شد فعلا نه 
تا آپدیت جدید آقای کرمعلی زاده

**Comment by brahmanzadeh** [comment]
مشکل هنوز حل نشده؟

**Comment by MASOODOK** [comment]
> 
> 
> مشکل هنوز حل نشده؟

خیر دوست عزیز همچنان مشکل وجود دارد ..
 ظاهراً همه چیز درست هست و لاگین میشه کرد ولی هنگام دانلود پیام خطا میده 
نمونه پیام خطا در فایل لاگ نشون میده که استریم با خطا متوقف میشه
نمونه خطا :

[http @ 0x558d19d9c280] HTTP error 420 
http://msx.namava.ir/hvod/2019/8/e470f318-1ade-3e50-bb49-1532dbb0239d/v_1280.mp4/index-v1-a1.m3u8?x=6irG3Dg5eFfmeP_5_0fAjZhYnuNFlj6cRP6XdThr6K8PCsmZys7-RsCnUcb52F9laVvbtQRBwFpQPY_CZQ5yFiSyUd04GiDZkQfP7tsDhIOs1CNCiHHj9NIn9EmpHlGbPXp2mtUMOb9AI9TB-X6DUDmULaFcgLagrqvtYy59ePE1: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

**Comment by brahmanzadeh** [comment]
@NabiKAZ 
امیدی هست مشکل حل بشه؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

امروز یکم فرصت دارم روش کار کنم. فقط برای تست، اشتراک ندارم. قبلاً یکی دو تا فیلم رایگان بود روی اونها تست میکردم که الان پیدا نمیکنم.
یکی از دوستان لطف کنه یه اکانت برام بفرسته تلگرام @nabikaz بعد میتونه پسوردش رو عوض کنه.

**Comment by brahmanzadeh** [comment]
@NabiKAZ 
اشتراک رسید دستتون؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون از همکاری دوستانی که دسترسی ارسال کردند.
مشکل حل شد. لطفاً آپدیت و تست کنید.
