### ISSUE TITLE
فایل دانلود شده با اپ نماوا

### ISSUE THREAD

**Issue by najafi2725** [NabiKAZ/namava-downloader#27]
سلام 
یه برنامه خود نماوا داره که فیلم ها رو دانلود میکنه 
C:\User\Videos\Namava در این پوشه 
اما فقط با پلیر خودش اجرا میشه
امکانش هست همون فایل دانلود شده رو با روشی اجرا کرد؟
ایده خاصی به ذهنتون نمیرسه؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

اون رو امتحان نکردم و درموردش نمیدونم ولی خب فیلیمو هم همچین برنامه ای داره که حتی اگر بشه ویدیو رو ازش کشید بیرون، بازهم محدودیت هایی روی تعداد دانلود و... داره از طرفی خب چه کاریه! وقتی همین برنامه به شکل کاملاً مستقل و نامحدود میتونه ویدیوها رو دانلود کنه.
