### ISSUE TITLE
لاگین نمیشه

### ISSUE THREAD

**Issue by 3245** [NabiKAZ/namava-downloader#29]
وقتی تلاش برای لاگین میکنم. میزنه لاگین شد اما دوباره یوزر و پسورد میخواد
![image](https://user-images.githubusercontent.com/25947915/65372163-962e0100-dc81-11e9-957e-52dd4210c2b4.png)

**Comment by NabiKAZ** [comment]
<div dir=rtl>

من درست 3 روز قبل یه اصلاحیه در خصوص همین مشکل انجام دادم. حدس میزنم شما از نسخه قدیمی استفاده میکنید.
لطفاً آپدیت و تست مجدد کنید. اگر بازهم مشکل باقی بود در همین تیکت اطلاع دهید.
