### ISSUE TITLE
تصویر خراب

### ISSUE THREAD

**Issue by hamidbn** [NabiKAZ/namava-downloader#3]
سلام. تصویری که به عنوان پیش نمایش برای فیلم ها در قسمت دانلود نشان میدهد خراب است.همچنین امکان دانلود زیرنویس فیلم ها وجود ندارد

**Comment by NabiKAZ** [comment]
<div dir="rtl">
ممنون که اشکالات رو گزارش میکنید.

- مشکل عکس فیلم ها حل شد. (این به این خاطره که نماوا هر چند وقت یکبار یک سری تغییرات در سایتش میده و ما هم لازمه هر بار آپدیت هایی برای حل این مشکلات انجام بدیم)

- امکان دانلود زیرنویس هم تحت تیکت #4 کار شد.

اکنون میتوانید نسخه جدید را دانلود کنید. لطفاً دوباره تست کنید.
