### ISSUE TITLE
ارور 403

### ISSUE THREAD

**Issue by hmmilani** [NabiKAZ/namava-downloader#30]
سلام
من تا فایل 
download.php 
رو اجرا میکنم ارور 403 میگیرم.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فایل رو چجوری اجرا میکنید؟

**Comment by hmmilani** [comment]
متأسفانه من از برنامه نویسی خیلی سر در نمیارم، شما هم توضیح نداده بودید که
فولدر دانلود شده رو چه جوری استفاده کنم. برای همین فولدر رو همینجوری تو یه
آدرسی گذاشتم. مثلا داخل درایو c فولدر namava

 بعد از نصب php مجبور شدم در cmd بعد از تایپ php آدرس کامل download.php رو
وارد کنم. یعنی یه همچین چیزی:
php c:\\namava\download.php

که در این حالت یه چیزایی میشناخت مثلاً مشخصات برنامه و اسم شما رو می آورد
ولی به مرحله یوزر نیم و پسورد نمیرسید. و یه fatal error میداد.

برای همین از xampp استفاده کردم و فولدر رو در htdoc قرار دادم
و از مرورگر و آدرس localhost وارد فولدر مربوطه شدم و روی download.php کلیک
کردم که یه صفحه سفید باز می شد و می نوشت 403، البته وقتی از همین طریق روی
stat.php میزدم درست نشون میداد و اون حالت جدول بندی رو می آورد. منتها چون
چیزی دانلود نشده بود خالی بود.


خیلی ممنون میشم راهنمایی کنید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

این موارد که اصلاً ربطی به برنامه نویسی نداره. کار با چند تا برنامه سادست و شما بدون تخصص هم به سادگی میتونید اونها رو انجام بدید.

توضیح نحوه اجرای برنامه هم در صفحه اول پروژه و اینجا داده شده:
https://github.com/NabiKAZ/namava-downloader#%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87

کاری هم که شما کردید اشتباه نبوده و تحت خط فرمان باید اجرا کنید.

شما در هر مسیر دلخواه میتونید فایلهای برنامه رو کپی کنید و با همون دستوری که قبلاً در راهنما گفته شد اون رو در خط فرمان cmd اجرا کنید.
اگر لازم داشتید با دستور cd میتونید وارد مسیر جدید بشید.
برنامه تحت وب روی مرورگر و با آدرس localhost کار نخواهد کرد.

**Comment by hmmilani** [comment]
خب پس با این حساب به مشکل دیگری میخورم در cmd. برای فیلیمو هم همینطور بود.
عکسش رو براتون میفرستم...
[image: 0.jpg]

**Comment by NabiKAZ** [comment]
<div dir=rtl>

عکسی نمیبینم.

**Comment by hmmilani** [comment]
![0](https://user-images.githubusercontent.com/55908576/65936776-a5a00d80-e42a-11e9-8661-555312f56472.jpg)

**Comment by hmmilani** [comment]
https://imgurl.ir/viewer.php?file=a534031_.jpg

**Comment by NabiKAZ** [comment]
<div dir=rtl>

درمورد این خطا قبلاً اینجا راه حل رو عرض کردم:

https://github.com/NabiKAZ/namava-downloader/issues/13#issuecomment-439360805
