### ISSUE TITLE
امکان توقف و ادامه دادن دانلود

### ISSUE THREAD

**Issue by hmmilani** [NabiKAZ/namava-downloader#31]
سلام ابتدا تشکر می کنم بابت برنامه خوبتون. مشکلات قبلیم حل شد و دانلود انجام میشه.
سوالی که داشتم اینه که امکان ادامه دادن دانلود از جایی که دانلود قطع شده وجود نداره؟
یعنی در جدول گزارش گیری به هر دلیلی دانلود قطع شده ومثلاً در 75 درصد دانلود توقف کرده.
وقتی دستور رو دوباره تایپ و اجرا میکنیم از صفر شروع به دانلود می کنه.
خواستم بپرسم امکان اینکه از ادامه شروع به دانلود کنه نیست؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

از نظر فنی متأسفانه در حال حاضر این امکان وجود نداره.

اما شما میتونید یه vps کوچیک تهیه کنید و با سرعت و پایداری بیشتر ویدیوها رو روی سرور دانلود کنید؛ سپس با قابلیت استاپ و دانلود از ادامه و سرعت بالاتر و استفاده از حداکثر پهنای باند، توسط مثلاً IDM از روی سرورتون ویدیو رو دانلود کنید.
