### ISSUE TITLE
نمایش لینک دانلود

### ISSUE THREAD

**Issue by nopoir** [NabiKAZ/namava-downloader#32]
سلام 

امکانش هست که لینک دانلود فیلم را به کاربر نشون بده که کاربر بتونه با نرم افزار اینترنت دانلود منیجر دانلود کنه

**Comment by NabiKAZ** [comment]
<div dir=rtl>

متاسفانه به لحاظ فنی به شکل مستقیم این امکان وجود نداره چون ویدیو به صورت استریم دانلود میشود.
اما پیشنهاد من استفاده از یک سرور کوچک VPS است. که میتوانید روی آن دانلود کنید و سپس از آنجا به صورت دایرکت لینک و با حداکثر سرعت روی سیستم خود دانلود کنید.
