### ISSUE TITLE
از کار افتادن برنامه

### ISSUE THREAD

**Issue by mrmilgh** [NabiKAZ/namava-downloader#34]
سلام
خیلی ممنون از برنامه عالیتون
متاسفانه برنامه چند روزیه که از کار افتاده و مدام یوزر و پسورد میپرسه و از این مرحله جلوتر نمیره
احتمالا بخاطر ورژن جدید نماواس
میخواستم بدونم قصد بروزرسانی اسکریپتو ندارید؟

**Comment by NabiKAZ** [comment]
فرصت کنم حتماً اصلاحش میکنم.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

مشکل حل شد و لاگین و دانلود ویدیو با نسخه جدید نماوا سازگار شده است.
دقت داشته باشید که در زمان لاگین در قسمت یوزرنیم از شماره موبایل همراه با کد کشور به شکل کامل استفاده شود، به عنوان مثال:
<div dir=ltr>

`+989123456789`

**Comment by ahadzadeh** [comment]
سلام متاسفانه دوباره از کار افتاده لطفا بررسی بفرمایید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پروژه را بروز کنید.

این مطلب درمورد مشکل ورژن ffmpeg رو بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350
