### ISSUE TITLE
کار نکردن برنامه 

### ISSUE THREAD

**Issue by mohammadsaleh85** [NabiKAZ/namava-downloader#36]
احتمالا بعلت تغییر سایت نماوا نرم افزار شما لاگین نمی شود لطفا اگر می توانید راهنمایی کنید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

موضوع تکراری، لطفاً در ایشیو زیر پیگیری شود:
Duplicate: https://github.com/NabiKAZ/namava-downloader/issues/34
