### ISSUE TITLE
ساختن ورژن جدید

### ISSUE THREAD

**Issue by mohammadsaleh85** [NabiKAZ/namava-downloader#37]
لطفا هرچه زودتر ورژن جدیدش رو بارگذاری کنید تا تمام مشکلات رفع بشه چون نرم فزار خیلی خوبی هست و واقعا بهش نیاز دارم اگه زود تر به کار بیافته جای حمایت زیادی داره ممنون

**Comment by NabiKAZ** [comment]
<div dir=rtl>

موضوع تکراری، لطفاً در ایشیو زیر پیگیری شود:
Duplicate: https://github.com/NabiKAZ/namava-downloader/issues/34
