### ISSUE TITLE
مشکل در ورود نام کاربری و رمز عبور

### ISSUE THREAD

**Issue by mojtabahub** [NabiKAZ/namava-downloader#38]
با سلام و عرض خسته نباشید
نام کاربری و رمز عبور رو میزنم پیغام خطای زیر رو میده
Logging...
PHP Notice:  Undefined offset: 1 in C:\namava\download.php on line 32

Notice: Undefined offset: 1 in C:\namava\download.php on line 32
Logged In.
IMPORTANT: Your private cookies is stored in the 'config/' directory, Be careful about its security!
===========================================================

قبلا لاگین میشدم این مشکل رو نداشتم
اشکال از کجاست؟

**Comment by mohammadsaleh85** [comment]
برای من هم این مشکل پیش آمده احتما به دلیل تغییرات جدید سایت نماوا است باید منتظر ورژن جدید این برنامه باشیم

**Comment by samiref** [comment]
سلام

فعلا میتونید از این استفاده کنید تا زمانی که تغییرات را روی ورژن اصلی بذارند

https://github.com/seyyed-amir/namava-downloader

**Comment by mohammadsaleh85** [comment]
خیلی ممنون

**Comment by mojtabahub** [comment]
ممنونم، حل شد مثل اینکه

**Comment by mohammadsaleh85** [comment]
خوبه حل شد اما از حجم اینترنت بیشتر از حجم فیلم کم می کنه در صورتی که باید حجم مصرفی مبین نت برای نماوا رایگان باشه

**Comment by mohammadsaleh85** [comment]
اگه راهی وجود داره لطفا راهنمایی کنید

**Comment by nopoir** [comment]
سلام.برای من همین این مشکل را داره 

PHP Notice:  Undefined offset: 1 in C:\nam\download.php on line 31
Notice: Undefined offset: 1 in C:\nam\download.php on line 31

**Comment by NabiKAZ** [comment]
<div dir=rtl>

موضوع تکراری، لطفاً در ایشیو زیر پیگیری شود:
Duplicate: https://github.com/NabiKAZ/namava-downloader/issues/34
(مسئله در همان تیکت حل شده است)
