### ISSUE TITLE
💵 دونیشن‌های شما همراه با ❤️

### ISSUE THREAD

**Issue by NabiKAZ** [NabiKAZ/namava-downloader#39]
<div dir=rtl>

دوستان خوبم!
لطفاً اگر دونیشنی انجام دادید، اینجا پیام بگذارید تا براتون ❤️ بفرستم 😉

پرداخت آنلاین:
https://zarinp.al/nabikaz
_(لطفاً حتماً در توضیحات آن، نام این پروژه را ذکر کنید)_

**Comment by zitanix** [comment]
عالی بود
مبلغ ناچیزی اهدا شد

**Comment by NabiKAZ** [comment]
@zitanix
<div dir=rtl>
سپاس بزرگوار <3
