### ISSUE TITLE
.........

### ISSUE THREAD

**Issue by NasaKHw** [NabiKAZ/namava-downloader#40]
....

**Comment by NabiKAZ** [comment]
<div dir=rtl>

نکته ای که وجود داره اینه که نماوا در نسخه جدیدش برای سریال ها برای هر اپیزود یک صفحه جدید نداره، بنابراین شما تنها آیدی فصل رو میبینید که به کار ما نمیاد. شما اون قسمت رو پخش کنید تا بالای صفحه آیدی رو ببینید.
برای مثال این صفحه اصلی سریاله:
https://www.namava.ir/series/19063-breaking_bad
شما روی قسمت اول کلیک کنید و به چنین لینکی هدایت میشید: (که فیلم شروع به پخش میکنه)
https://play.namava.ir/?m=19553&p=desktop
خب در اینجا آیدی مورد نظر ما 19553 است و نه 19063 که باید تحویل برنامه بدید برای دانلودش.

درمورد زیرنویس ها هم مشکلی ندیدم و اگر فیلم زیرنویس فارسی داشته باشه دانلودش میکنه توی همون شاخه download

پرداخت هزینه هم که اشاره کردید به شکل دونیشن کاملاً اختیاریه که در اینجا توضیح دادم:
https://github.com/NabiKAZ/namava-downloader#%D8%AD%D9%85%D8%A7%DB%8C%D8%AA

**Comment by NabiKAZ** [comment]
<div dir=rtl>

خلاصه مکالمه با دوستمون روی تلگرام رو اینجا میگذارم شاید حاوی نکاتی باشه و این مشکل، مشکل شما هم باشه.

<hr>

Nabi, [18.01.20 23:42]
مشکلی این سمت نمیبینم
```
Input Video ID: 19050
Title: برکینگ بد - فصل ۱ قسمت ۱
===========================================================
Select Quality:
1) BANDWIDTH=197407 - RESOLUTION=270x152
2) BANDWIDTH=243221 - RESOLUTION=360x202
3) BANDWIDTH=312893 - RESOLUTION=480x270
4) BANDWIDTH=415257 - RESOLUTION=640x360
5) BANDWIDTH=593800 - RESOLUTION=854x480
6) BANDWIDTH=1011092 - RESOLUTION=1280x720
7) BANDWIDTH=1839076 - RESOLUTION=1920x1080
Input option number:
```
Nabi, [18.01.20 23:46]
روی سروری که دارید میزنید یه چیزی درست نیست. یا دسترسی به جایی قطع شده یا مثلاً اون cdn یی که این فیلم روشه مثلاً بلاکه یه همچین چیزایی به ذهنم میرسه...

Nabi, [19.01.20 00:07]
دارم نگاش میکنم. ظاهراً روی برخی ویدیوها روی سرور شما 404 برمیگرده که خیلی عجیبه!!!
```
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Sat, 18 Jan 2020 20:30:50 GMT
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: -1
< Vary: Accept-Encoding
< X-Leah-Ver: 1
<
* Connection #0 to host www.namava.ir left intact
string(0) ""
NULL
```
Nabi, [19.01.20 00:09]
[In reply to Not ⠀Empty⠀]
آره مشکل اکانت نیست.
هر چیه توی سروره.

Nabi, [19.01.20 00:18]
به نظر مشکل از DNS سرورتون هست.
بعضی آدرسها رو باز نمیکنه.
نماوا آی پی های مختلفی داره برا CDN سرورهاش
همون حدس اولیه.
یعنی برخی از روی سرور شما resolve نمیشن

Nabi, [19.01.20 00:20]
اینجا میبینید برای دو ویدیو با آیدی مختلف داره IP های مختلفی رو میبینه:
```
Input Video ID: 19050
* Hostname www.namava.ir was found in DNS cache
*   Trying 94.182.100.133...
* Connected to www.namava.ir (94.182.100.133) port 443 (#0)

Input Video ID: 26630
* Hostname www.namava.ir was found in DNS cache
*   Trying 94.182.176.33...
* Connected to www.namava.ir (94.182.176.33) port 443 (#0)
```
Nabi, [19.01.20 00:23]
اگر روی سرور بزنید:
lynx https://www.namava.ir/api2/movie/19050
خطای 404 میده.

ولی بزنید:
lynx https://www.namava.ir/api2/movie/26630
محتوا باز میشه.

این در حالیه که هر دوی این آدرسها روی سیستم من دارن باز میشن و تنها روی سرور شما اینطوریه.
که این نشون میده مشکل در سطح DNS سرور شما وجود داره و البته یا اینکه خود نماوا داره محدودیت خاصی روی برخی IP های ورودی اعمال میکنه.
البته روی یه سرور آلمان هم همین مشکل رو دیدم. اما روی سرور ایران دیگه مشکلی نبود.

Nabi, [19.01.20 00:24]
عجیبه سرورتون هم ایرانه ظاهراً.

Nabi, [19.01.20 00:26]
دی ان اس سرورتون /etc/resolv.conf رو دست کاری کردم فایده نداشت. ممکنه از سمت خود نماوا مسدود شده باشید.

Nabi, [19.01.20 00:26]
شاید بشه از پروکسی استفاده کرد.


![photo_2020-01-19_01-14-06](https://user-images.githubusercontent.com/246721/72670961-08102e80-3a59-11ea-9fc6-c061eb5de4d8.jpg)
![photo_2020-01-19_01-14-08](https://user-images.githubusercontent.com/246721/72670962-0a728880-3a59-11ea-9677-097c74d5e5c1.jpg)


Nabi, [19.01.20 00:57]
مشکل روی DNS نیست.
میبینید از توی سرور یک ویدیو پخش میشه و دیگری پخش نمیشه!
با توجه به اینکه سرور شما هم ایرانه، این فرضیه رد میشه که مثلاً نماوا به خاطر کپی رایت مثلاً دسترسی خارجی ها رو به محتوای فیلم های خارجی رو از عمد مسدود کرده!

Nabi, [19.01.20 00:59]
ولی هر چی هست باید از سمت خود نماوا باشه که دسترسی از برخی IP ها رو به برخی فیلم ها رو مسدود کرده.

پروکسی رو میشه بیشتر روش کار کرد و تست زد...

و البته به نظرم حتماً از طریق پشتیبانی نماوا مسئله رو پیگیری کنید و بگید که از IP شما، دسترسی به برخی فیلم ها وجود نداره.

Nabi, [19.01.20 01:02]
[In reply to Not ⠀Empty⠀]
اصلاً برای استفاده تجاری که پیشنهاد نمیکنم چون اخلاقی هم نیست:
https://github.com/NabiKAZ/namava-downloader#%D8%B1%D9%81%D8%B9-%D9%85%D8%B3%D8%A6%D9%88%D9%84%DB%8C%D8%AA

ولی من از جنبه فنی دارم صحبت میکنم و خودم کنجکاوم بیشتر...

Nabi, [19.01.20 01:03]
تونل زدم از سرور شما و آی پی سیستم خودم رو به آی پی سرور شما تغییر دادم. روی سیستم خودم اون ویدیو خاص باز نشد.
الان دیگه میتونم مطمئن باشم IP شما دسترسی باز کردن برخی ویدیوها رو نداره.
که این نوع از محدودیت از سمت نماوا میتونه عجیب باشه.
بنابراین به نظرم از طریق پشتیبانی مطرح کنید و علت رو جویا بشید.
به من هم بگید 😉

**Comment by NabiKAZ** [comment]
<div dir=rtl>

بخوام جمع بندی کنم. در کل سه راه دارید:

1. پروکسی های مختلف رو تست کنید تا بالاخره شاید یکیشون کار کنه، توی کد هم پیشبینی شده و کافیه حدود خط 13 متغییر $proxy رو مقدار دهی کنید مثلاً به شکل 127.0.0.1:9150 (البته احتمالاً اگر مجبور بشید حتماً IP ایرانی رو استفاده کنید، پیدا کردن پروکسی ایرانی شاید کمی دشوار باشه)

2. سرورتون رو کلاً عوض کنید و قبلش مطمئن بشید از اون سرور به فیلم های مورد نظر دسترسی وجود داره.

3. با پشتیبانی نماوا تماس بگیرید و علت مسدود بودن IP برای برخی فیلمها رو جویا بشید و درخواست رفع مسدود سازی کنید. که با توجه به اینکه IP سرور شما ایرانه، قائداً باید همکاری کنند و مشکل رو حل کنند.

پیشنهاد من گزینه 3 است.
