### ISSUE TITLE
صفر نشون دادن حجم

### ISSUE THREAD

**Issue by aryanveisi** [NabiKAZ/namava-downloader#41]
سلام وقت بخیر من وقتی کیفیت رو انتخاب میکنم میزنه :
Video file: download/38352_265537.mp4
Cover file: download/38352_265537.jpg
Subtitle file: download/38352_265537.srt
Log file: download/38352_265537.log
Info file: download/38352_265537.info
Start downloading in the background...
You can see stats download with 'stats.php' in the web page.
For stop process, kill it.
Bye!

توی لوکال هاست هم چک میکنم حجم رو میزنه صفر

**Comment by NabiKAZ** [comment]
<div dir=rtl>
حدود 10 خط آخر فایل log رو لطفاً اینجا بزارید.

**Comment by aryanveisi** [comment]
file log koja hastesh ?

**Comment by aryanveisi** [comment]
پیدا کردم
sh: ffmpeg: command not found

**Comment by NabiKAZ** [comment]
<div dir=rtl>

خب پس مشخصه، باید ffmpeg رو نصب کنید:
http://ffmpeg.org
