### ISSUE TITLE
عدم دانلود و تولید خطای Error when loading first segment...

### ISSUE THREAD

**Issue by mrmilgh** [NabiKAZ/namava-downloader#43]
سلام
متاسفانه اسکریپت مدتیه کاملا از کار افتاده و فایل mp4 نمیگیره فقط عکس و زیرنویس میگیره
و الانم که پروکسی ست میکنم کلا لوگین نمیکنه توی اکانت
با پروکسی های مختلف امتحان کردم.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

من الان تست کردم مشکل خاصی ندیدم.
لطفاً مطمئن بشید آخرین نسخه رو دانلود کردید.
اگر بازم مشکل باقی بود، چند خط آخر فایل log رو لطفاً بزارید اینجا.

**Comment by mrmilgh** [comment]
بله آخرین نسخه هستش
این آخرین خط فایل لاگ خدمت شما :
[hls @ 000001c00b138a40] Error when loading first segment 'https://msx.namava.ir/hvod/2020/2/217c7ed7-d36e-42d3-adc9-87958c857de3/v_854.mp4/seg-1-v1-a1.ts?x=hBZqPd33EGTxKfLkU50AwcBIQOqQpKwtT5D2HltQO2tgRSCJ0x5PS8iwTvnxf6z-8iDZCWL8-QkGUetRNUXpDSX_Z1IYqtetI8MjvPkfGBuh5OELVAwmQBeQymj3pb7F9_unO3jrK1ZRDk0RZswlajYla_-6Fdz0h0CBbGzH2Rw1'
https://msx.namava.ir/hvod/2020/2/217c7ed7-d36e-42d3-adc9-87958c857de3/v_854.mp4/index-v1-a1.m3u8?x=hBZqPd33EGTxKfLkU50AwcBIQOqQpKwtT5D2HltQO2tgRSCJ0x5PS8iwTvnxf6z-8iDZCWL8-QkGUetRNUXpDSX_Z1IYqtetI8MjvPkfGBuh5OELVAwmQBeQymj3pb7F9_unO3jrK1ZRDk0RZswlajYla_-6Fdz0h0CBbGzH2Rw1: Invalid data found when processing input

واسه آیدی های مختلف تست کردم همین وضعیته
پروکسی هم که ست میکنم کلا لوگین نمیکنه که بخواییم به این مراحل برسیم.

**Comment by itispey** [comment]
سلام
، منم مشکل کریپتو رو دارم...
میدونم این مشکلات برای ffmpeg 
هست اما چطور میشه برطرفشون کرد؟؟
Error log:
```
ffmpeg version git-2020-02-06-343ccfc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 39.100 / 56. 39.100
  libavcodec     58. 68.100 / 58. 68.100
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 74.100 /  7. 74.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[https @ 00000200afb3a440] No trailing CRLF found in HTTP header. Adding it.
[hls @ 00000200afb39240] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 00000200afb39240] Skip ('#EXT-X-VERSION:3')
[hls @ 00000200afb39240] Opening 'https://msx.namava.ir/hvod/2020/2/7217c3ba-1ec5-4670-bd33-b09bd8198c7e/v_1280.mp4/encryption.key?x=YWxWg1oAwvcZZmtKyTfI976h3PaeK0iAOJZGFWThYumVmzSvzPLgaVKZzeQqkvvEkeC6TqqygwQmkZvCA51XqM_XIFQo-wFXkUBc54w7Eskv01vM-x0wz5a-cU4a8nRjl5CmNcYJu8XUmK7O8B2bxbabKM3tIyJuS-1GPZ0QVsM1' for reading
[hls @ 00000200afb39240] Opening 'crypto+https://msx.namava.ir/hvod/2020/2/7217c3ba-1ec5-4670-bd33-b09bd8198c7e/v_1280.mp4/seg-1-v1-a1.ts?x=YWxWg1oAwvcZZmtKyTfI976h3PaeK0iAOJZGFWThYumVmzSvzPLgaVKZzeQqkvvEkeC6TqqygwQmkZvCA51XqM_XIFQo-wFXkUBc54w7Eskv01vM-x0wz5a-cU4a8nRjl5CmNcYJu8XUmK7O8B2bxbabKM3tIyJuS-1GPZ0QVsM1' for reading
[crypto @ 00000200afb8d140] Unable to open resource: https://msx.namava.ir/hvod/2020/2/7217c3ba-1ec5-4670-bd33-b09bd8198c7e/v_1280.mp4/seg-1-v1-a1.ts?x=YWxWg1oAwvcZZmtKyTfI976h3PaeK0iAOJZGFWThYumVmzSvzPLgaVKZzeQqkvvEkeC6TqqygwQmkZvCA51XqM_XIFQo-wFXkUBc54w7Eskv01vM-x0wz5a-cU4a8nRjl5CmNcYJu8XUmK7O8B2bxbabKM3tIyJuS-1GPZ0QVsM1
[hls @ 00000200afb39240] Error when loading first segment 'https://msx.namava.ir/hvod/2020/2/7217c3ba-1ec5-4670-bd33-b09bd8198c7e/v_1280.mp4/seg-1-v1-a1.ts?x=YWxWg1oAwvcZZmtKyTfI976h3PaeK0iAOJZGFWThYumVmzSvzPLgaVKZzeQqkvvEkeC6TqqygwQmkZvCA51XqM_XIFQo-wFXkUBc54w7Eskv01vM-x0wz5a-cU4a8nRjl5CmNcYJu8XUmK7O8B2bxbabKM3tIyJuS-1GPZ0QVsM1'
https://msx.namava.ir/hvod/2020/2/7217c3ba-1ec5-4670-bd33-b09bd8198c7e/v_1280.mp4/index-v1-a1.m3u8?x=YWxWg1oAwvcZZmtKyTfI976h3PaeK0iAOJZGFWThYumVmzSvzPLgaVKZzeQqkvvEkeC6TqqygwQmkZvCA51XqM_XIFQo-wFXkUBc54w7Eskv01vM-x0wz5a-cU4a8nRjl5CmNcYJu8XUmK7O8B2bxbabKM3tIyJuS-1GPZ0QVsM1: Immediate exit requested
Exiting normally, received signal 15.
```

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

فرصتی دست داد که یک بررسی روی موضوع داشته باشم.
در خصوص خطایی که دوستان بالا اشاره کردند (Error when loading first segment...)
یک مقدار موضوع عجیب بود و در برخی ورژن های ffmpeg مشاهده شده است. طرح موضوع و جزئیات فنی و پیشرفت حل مسئله در [این لینک ](https://video.stackexchange.com/questions/32679/ffmpeg-works-in-linux-and-same-command-in-windows-get-me-error-invalid-data-foun)مطرح شده است که هنوز به سرانجام نرسیده.
آخرین احتمال این است که یک باگ از نسخه `ffmpeg >= 4.3` وجود داشته باشد.
باگ در [اینجا](http://trac.ffmpeg.org/ticket/8998) گزارش شده که توسط تیم توسعه ffmpeg درحال بررسی است.
بنابراین به عنوان یک راه حل، فعلاً میشود گفت که از ffmpeg نسخه های 3.0 و یا بالاتر و حداکثر 4.2.3 یا کمتر از آن استفاده کنید.
بنده روی نسخه های مختلف آزمایش کردم و نتایج آنها بدین صورت بود:


| نسخه  | وضعیت |
| ------------- | ------------- |
| ffmpeg-1.0.1-win64-static | Error in the pull function. |
| ffmpeg-1.2-win64-static | Error in the pull function. |
| ffmpeg-2.0.1-win64-static | Error in the pull function. |
| ffmpeg-2.2.3-win64-static | Error in the pull function. |
| ffmpeg-3.0-win64-static | OK |
| ffmpeg-3.1.5-win64-static | OK warning... |
| ffmpeg-3.2.4-win64-static | OK |
| ffmpeg-3.3.4-win64-static | OK |
| ffmpeg-3.4.2-win64-static | OK |
| ffmpeg-4.0.2-win64-static | OK |
| ffmpeg-4.1.4-win64-static | OK |
| ffmpeg-4.2.3-win64-static | OK |
| ffmpeg-4.3-win64-static | Error when loading first segment |
| ffmpeg-4.3.1-win64-static | Error when loading first segment |
| ffmpeg-2020-11-18-git-e3081d6f4f | Error when loading first segment |

نسخه های مختلف را از لینک زیر میتوانید دانلود کنید:
https://www.videohelp.com/software/ffmpeg/old-versions

لینک مستقیم جدیدترین نسخه ای که در تست بنده بدون مشکل کار کرد یعنی 4.2.3 را از لینکهای زیر میتوانید دانلود کنید:

ویندوز 64 بیتی:
https://www.videohelp.com/download/ffmpeg-4.2.3-win64-static.zip

ویندوز 32 بیتی:
https://www.videohelp.com/download/ffmpeg-4.2.3-win32-static.zip

مک:
https://www.videohelp.com/download/ffmpeg-4.2.3-macos64-static.zip

سورس جهت کمپایل روی لینوکس:
https://www.videohelp.com/download/ffmpeg-4.2.3.tar.bz2
