### ISSUE TITLE
مشکل در اجرا

### ISSUE THREAD

**Issue by mhanit** [NabiKAZ/namava-downloader#44]
<div dir=rtl>

سلام با عرض خسته نباشید
من تمام فایل ها رو دانلود کردم 
و فایل download.php رو در مسیر 127.0.0.1 اجرا کردم که یکسری کد عجیب داد 
و نرم افزار PUTY رو نمی فهمم چه جوری اینجا استفاده کنم 
اگر یک راهنمای کلی بفرمایید ممنون میشم

**Comment by NabiKAZ** [comment]
<div dir=rtl>

یک سری کد عجیب داد؟! به نظر شما بدون دونستن اونها چطور میتونم راهنمایی کنم؟ :-)

putty برای اتصال به یک سرور استفاده داره.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

با توجه به گذشت زمان زیاد، تیکت بسته میشود، چنانچه موضوع برای شما هنوز حل نشده بود، با ذکر جزئیات بیشتر میتوانید تیکت را دوباره باز کنید.
