### ISSUE TITLE
مشکل در دانلود فایل + چند سوال درباره API ها

### ISSUE THREAD

**Issue by itispey** [NabiKAZ/namava-downloader#46]
با سلام.
من در دانلود فایل توسط این اسکریپت مشکلی دارم که توی سایر ریکوئیست ها دوستان بهشون اشاره کردن نیازی نیست مجدد اینجا بگم.
مسئله ای که واسم سوال بود این بود که شما ای پی آی رو از کجا پیدا کردید؟ ای پی آی لاگین کردن و وریفای کردن کاربر منظورم بود.
من دارم با کمک گرفتن از سورس شما یه اسکریپت به زبان سی شارپ می نویسم... زمانی که از وب سرویس
`https://www.namava.ir/api/v1.0/accounts/by-phone/login`
جهت لاگین کردن استفاده میکنم، نام کاربری و پسورد رو به صورت آرایه ارسال میکنم. زمان ارسال نام کاربری و پسورد اشتباه با ارور:
*Code: 10602, Message: Invalid username or password*
مواجه میشم که نشون میده وب سرویس به درستی کار میکنه و پاسخ میده.
اما زمانی که از نام کاربری و پسورد صحیح حساب کاربری خودم استفاده میکنم با این ارور مواجه میشم:
```
{
    "Message": "An error has occurred."
}
```
همین!! نه دلیلشو میگه نه کدش رو...
میدونید این مشکل از چیه؟

ممنون برای خوندن این پیام :)

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر در پاسخگویی.

آدرس api ها رو از developer tools کروم تب network میتونید ببینید.
خطایی هم که اشاره کردید خیلی مبهمه و کافی نیست برای اینکه بشه حدس زد مشکل کجاست. اما از همون مسیری که اشاره کردم، رکوئست کامل به اون آدرس رو همراه هدر و پارامترها و سایر جزئیات رو میتونید ببینید و در برنامه خودتون لحاظ کنید، شاید مشکل شما اینطور حل شد.
