### ISSUE TITLE
ارور curl_init برای زدن دستور php download.php

### ISSUE THREAD

**Issue by alimosavii98** [NabiKAZ/namava-downloader#47]
سلام و وقت بخیر خدمت دوست عزیز
وقتی دستور php download.php را میزنم
با این خطا مواجه میشم
راه حل چیه؟
![image](https://user-images.githubusercontent.com/61449583/75223122-04d83300-57bb-11ea-9774-8c4edb1ba3d1.png)

**Comment by mindthreads** [comment]
سلام

> سلام و وقت بخیر خدمت دوست عزیز
> وقتی دستور php download.php را میزنم
> با این خطا مواجه میشم
> راه حل چیه؟
> ![image](https://user-images.githubusercontent.com/61449583/75223122-04d83300-57bb-11ea-9774-8c4edb1ba3d1.png)

سلام
برنامه زیر رو دانلود و نصب کنید. از پی اچ پی موجود در زیر پوشه همین برنامه استفاده کنید
Xampp

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پروژه را بروز کنید.

این مطلب درمورد خطای curl را بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/63

این مطلب درمورد مشکل ورژن ffmpeg رو بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

**Comment by NabiKAZ** [comment]
Duplicate of #63
