### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by hmmilani** [NabiKAZ/namava-downloader#48]
سلام
من در
php.ini
فعال کردم
curl
رو، ولی این ارور پابرجاست

**Comment by mindthreads** [comment]
سلام منم همین مشکل رو داشتم
Xampp
رودانلود کردم، کامل نصب کردم و از 
php 
موجود در زیر پوشه همین برنامه استفاده کردم مشکل حل شد. فکر کنم ورژن پی اچ پی 7.4.3 بود

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پروژه را بروز کنید.

این مطلب درمورد خطای curl را بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/63

این مطلب درمورد مشکل ورژن ffmpeg رو بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

**Comment by NabiKAZ** [comment]
Duplicate of #63

**Comment by mindthreads** [comment]
درود‌بر شما
ممنوپ از توضیحاتتون
