### ISSUE TITLE
نحوه دانلود فیلم های دو زبانه 

### ISSUE THREAD

**Issue by mohammadsaleh85** [NabiKAZ/namava-downloader#49]
بعضی فیلم ها در نماوا دارای دو زبان و زیرنویس هستند آیا امکان انتخاب فیلم بازبان اصلی یا دوبله وجود دارد؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

زیرنویس دانلود میشود.
اما برای فیلم های دو زبانه اگر دو صوت مختلف وجود دارد، پشتیبانی نمیشود.
لطفاً یک نمونه فیلم را بفرمائید تا بررسی و این ویژگی اضافه شود.

**Comment by mohammadsaleh85** [comment]
![namava](https://user-images.githubusercontent.com/59120728/100061092-c7383180-2e42-11eb-836d-1dc0a82e65d7.png)
معمولا توی اکثر فیلم هایی که نماوا با دوبله اختصاصی می زاره امکان انتخاب زبان صدا و زیرنویس وجود داره مثلا فیلم جوکر اگه امکان داره امکان انتخاب زبان صدا و زیرنویس رو مثل انتخاب کیفیت به دانلودر اضافه کنید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

حرفتون سند بود، منظورم اثبات موضوع یا نشون دادن اینکه کجاش دو زبانه رو نشون میده، نبود. 😅 
منظورم لینک یک ویدیو یا آی دی اون بود که بتونم روش کار کنم 😉 
البته میتونم جوکر رو سرچ کنم ولی شما آیدیشو بدید کارمو ساده کنید :-)

**Comment by mohammadsaleh85** [comment]
این هم آیدی فیلم 31425 اگه نیاز داشتید می تونم اشتراک نماوا رو هم در اختیارتون قرار بدم تا بتونید راحتتر این کار رو ادامه بدید به نظر من این پروژه خیلی مفیده و می تونه بهتر هم بشه

**Comment by amoradi1355** [comment]
داداش کمکی میکنه منم بتونم دانلود کنم
