### ISSUE TITLE
سوال curl_init

### ISSUE THREAD

**Issue by Matintech** [NabiKAZ/namava-downloader#51]
سلام من اون چیزایی که گفتی رو نصب کردم و دستور رو اجرا کردم ولی این خطا رو میده 
Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\namava-downloader-master\download.php:140
Stack trace:
#0 C:\namava-downloader-master\download.php(17): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\namava-downloader-master\download.php on line 140
به زبان خیلی ساده بگو چه کنم؟ مرسی
mehdidj201290@yahoo.com 
 اگه شد ایمیل بده بهم. خیلی ممنون

**Comment by NabiKAZ** [comment]
Duplicate of #63
