### ISSUE TITLE
بلد نیستم دانلود کنم

### ISSUE THREAD

**Issue by AKARIMI97** [NabiKAZ/namava-downloader#52]
سلام من PHP و ffmpeg روهم نصب کردم ولی بلد نیستم دانلود کنم میشه از مراحل و کارهایی که بای انجام داد فیلم بگیرید و برای ایمیل من بفرستید
dra.karimi97@gmail.com
سپاس

**Comment by NabiKAZ** [comment]
<div dir=rtl>

در صفحه اول پروژه راهنمای گام به گام نصب و اجرای برنامه آمده است:
https://github.com/NabiKAZ/namava-downloader
شما دقیقاً در کدام مرحله مشکل دارید؟
