### ISSUE TITLE
دیگه کار نمیکنه

### ISSUE THREAD

**Issue by 3245** [NabiKAZ/namava-downloader#53]
سلام
دیگه کار نمیکنه. مشکلش چی هست؟ ممکنه فیکس کنید؟

**Comment by zitanix** [comment]
تست شد و کاملا بدون مشکل کار میکنه

**Comment by mohammadsaleh85** [comment]
من امروز امتحان کردم کار نمی کرد در لوگین کردن در سایت نماوا به مشکل خورده اگر امکان داره بررسی بشه

**Comment by green1112** [comment]
سلام .
کار میکنه
 ولی
 فایل mp4 
دانلود نمیشه

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پیام شما مربوط به چند ماه پیش بوده، آخرین نسخه پروژه را اکنون تست کنید و البته در مورد نسخه صحیح ffmpeg این مطلب را حتماً مطالعه کنید:

https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

در صورتی که مشکل شما حل نشده بود، جزئیات فنی بیشتری قرار دهید تا بررسی شود.
