### ISSUE TITLE
بررسی مشکل curl_init

### ISSUE THREAD

**Issue by mohammadrmr** [NabiKAZ/namava-downloader#54]
سلام دوست عزیز 
بفرمایین که این کدتون هنوز کار میکنه؟
من کارهای لازمو کردم ولی فتل ارور داد بهم

C:\namava>php download.php
Namava Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: https://www.namava.ir/
Project link: https://github.com/NabiKAZ/namava-downloader
===========================================================

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\namava\download.php:140
Stack trace:
#0 C:\namava\download.php(17): get_contents('https://www.nam...')
#1 {main}
  thrown in C:\namava\download.php on line 140

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پروژه را بروز کنید.

این مطلب درمورد خطای curl را بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/63

این مطلب درمورد مشکل ورژن ffmpeg رو بخونید:
https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

**Comment by NabiKAZ** [comment]
Duplicate of #63
