### ISSUE TITLE
عدم پیشرفت دانلود

### ISSUE THREAD

**Issue by aliyarX** [NabiKAZ/namava-downloader#55]
دانلود فایل پیشرفت نمیکند، خلاصه‌ی لاگ دریافتی بصورت زیر است

### 35134_2111547.log

> ffmpeg version git-2020-06-17-0b3bd00 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 55.100 / 56. 55.100
  libavcodec     58. 92.100 / 58. 92.100
  libavformat    58. 46.101 / 58. 46.101
  libavdevice    58. 11.100 / 58. 11.100
  libavfilter     7. 86.100 /  7. 86.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[https @ 000001da999fd940] No trailing CRLF found in HTTP header. Adding it.
[hls @ 000001da999fc740] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 000001da999fc740] Skip ('#EXT-X-VERSION:3')
[hls @ 000001da999fc740] Opening 'https://msx.namava.ir/hvod/2019/12/83db3078-01ad-4a76-bf8c-06252290c751/v_1920.mp4/encryption.key?x=xuDzNZez20of010CelzyCjLtQWdOmyrP8EiDVuoeiFA6Mb-D90VaW0U9y9XJMCYLMEV3rCYwbsN8_dTUYumghOdg8vw6lwaBNH0VESVBI3JDkB6Pyswwb9n428AE8nuNWM5Z-TeceyguYZgR82MZ8BD-qQ-UHFFp8gaXICGyS5k1' for reading
[hls @ 000001da999fc740] Opening 'crypto+https://msx.namava.ir/hvod/2019/12/83db3078-01ad-4a76-bf8c-06252290c751/v_1920.mp4/seg-1-v1-a1.ts?x=xuDzNZez20of010CelzyCjLtQWdOmyrP8EiDVuoeiFA6Mb-D90VaW0U9y9XJMCYLMEV3rCYwbsN8_dTUYumghOdg8vw6lwaBNH0VESVBI3JDkB6Pyswwb9n428AE8nuNWM5Z-TeceyguYZgR82MZ8BD-qQ-UHFFp8gaXICGyS5k1' for reading
[hls @ 000001da999fc740] Opening 'crypto+https://msx.namava.ir/hvod/2019/12/83db3078-01ad-4a76-bf8c-06252290c751/v_1920.mp4/seg-2-v1-a1.ts?x=xuDzNZez20of010CelzyCjLtQWdOmyrP8EiDVuoeiFA6Mb-D90VaW0U9y9XJMCYLMEV3rCYwbsN8_dTUYumghOdg8vw6lwaBNH0VESVBI3JDkB6Pyswwb9n428AE8nuNWM5Z-TeceyguYZgR82MZ8BD-qQ-UHFFp8gaXICGyS5k1' for reading
.
.
.
[hls @ 000001da999fc740] Opening 'crypto+https://msx.namava.ir/hvod/2019/12/83db3078-01ad-4a76-bf8c-06252290c751/v_1920.mp4/seg-474-v1-a1.ts?x=xuDzNZez20of010CelzyCjLtQWdOmyrP8EiDVuoeiFA6Mb-D90VaW0U9y9XJMCYLMEV3rCYwbsN8_dTUYumghOdg8vw6lwaBNH0VESVBI3JDkB6Pyswwb9n428AE8nuNWM5Z-TeceyguYZgR82MZ8BD-qQ-UHFFp8gaXICGyS5k1' for reading
[hls @ 000001da999fc740] Opening 'crypto+https://msx.namava.ir/hvod/2019/12/83db3078-01ad-4a76-bf8c-06252290c751/v_1920.mp4/seg-475-v1-a1.ts?x=xuDzNZez20of010CelzyCjLtQWdOmyrP8EiDVuoeiFA6Mb-D90VaW0U9y9XJMCYLMEV3rCYwbsN8_dTUYumghOdg8vw6lwaBNH0VESVBI3JDkB6Pyswwb9n428AE8nuNWM5Z-TeceyguYZgR82MZ8BD-qQ-UHFFp8gaXICGyS5k1' for reading

پس از مدتی طولانی که پیشرفتی حاصل نمیشود، ناچار به ترمینیت کردن پروسه میشوم

استفاده شده **`FFmpeg`** ورژن
> ffmpeg version git-2020-06-17-0b3bd00 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200523
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 55.100 / 56. 55.100
libavcodec     58. 92.100 / 58. 92.100
libavformat    58. 46.101 / 58. 46.101
libavdevice    58. 11.100 / 58. 11.100
libavfilter     7. 86.100 /  7. 86.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100

استفاده شده **`PHP`** ورژن 
> PHP 5.6.40 (cli) (built: Jan  9 2019 15:10:36)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

اگر اشتراک نماوا هم در دسترس ندارید، بفرمایید تا در اختیارتون قرار بدم، با تشکر فراوان از شما

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سپاس از لطف شما و همچنین اینکه توضیحات فنی کامل را بیان کردید.

حدس میزنم مشکل شما به تفاوت نسخه ffmpeg باشد که در این پست مفصل شرح داده شد:
https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350
