### ISSUE TITLE
امکان فراخوانی آی‌دی و کیفیت ویدیو از طریق آرگومان‌های تابع دانلود

### ISSUE THREAD

**Issue by bloorchi** [NabiKAZ/namava-downloader#56]
سلام
خیلی خوب می‌شد اگه می‌تونستیم تابع دانلود رو اینجوری کال کنیم:
php download.php 123456 7
که آرگومان اول کد ویدیو و آرگومان بعدی کیفیت باشه و برای کیفیت اگر مقدار صفر وارد شد کد خودش بالاترین کیفیت موجود رو از یست انتخاب کنه
سپاس

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون بابت پیشنهادتون، فکر خیلی خوبیه و در اولین فرصت آزاد میتونم روش کار کنم یا اگر دوستانی تونستن کد رو توسعه بدن میتونن pull request باز کنند تا با پروژه مرچ کنم.
