### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by amirmalek0** [NabiKAZ/namava-downloader#57]
این کدها دیگه کار نمیکنن وقتتون رو تلف نکنید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

پیام شما مربوط به چند ماه پیش بوده، آخرین نسخه پروژه را اکنون تست کنید و البته در مورد نسخه صحیح ffmpeg این مطلب را حتماً مطالعه کنید:

https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

در صورتی که مشکل شما حل نشده بود، جزئیات فنی بیشتری قرار دهید تا بررسی شود.
