### ISSUE TITLE
موقع زدن دستور php download.php ارور میده

### ISSUE THREAD

**Issue by Dark69Sea** [NabiKAZ/namava-downloader#58]
وقتی دستور اجرا میکنم میگه خط 140 مشکل داره با لینوکس امتحان کردم

**Comment by NabiKAZ** [comment]
<div dir=rtl>

با توجه به اینکه پروژه ممکن است هر لحظه تغییر کند، شماره خطوط اون هم تغییر میکنه، الان مشخص نیست خط 140 مورد نظر شما در آن زمان چی بوده است.
بنابراین یا از توی سورس لینک مستقیم به اون خط بدید که شماره مخزن هم توش باشه و یکتا باشه
و یا اینکه پیغام خطا و شرح ماجرا رو دقیقتر بیان کنید.
