### ISSUE TITLE
ارور 403

### ISSUE THREAD

**Issue by FreeMan1359** [NabiKAZ/namava-downloader#59]
سلام
هرکاری میکنم نمیدونم چرا ارور 403 می ده
دستورش اینه
if (php_sapi_name() !== "cli") exit("403");
لطفا اگر کسی میدونه دلیلش چی هست و راه حل چیه راهنمایی کنه
 و اینکه لطفا بفرمایی این برنامه لانم کار میکنه یا نه؟

**Comment by FreeMan1359** [comment]
از نرم افزار 
xampp
استفاده میکنم و ویندوز 10 پورت هم تغییر دادم

**Comment by FreeMan1359** [comment]
کلا با براوزر که میرم این خطا رو میداد که متوجه شدم باید با دستور کامند میرفتم
و حالا یه مشکل دیگه دارم که میگه
Could not open input file: php.download

**Comment by FreeMan1359** [comment]
برنامه بالاخره اجرا شد ولی فقط کاور دانلود شده و فیلم اصلی دانلود نمیشه
برای من تا ایجا پیشرفت خوبی بود ولی نتیجه کامل نداشت

**Comment by FreeMan1359** [comment]
[hls @ 000001babf1bd8c0] Opening 'crypto+https://media.namava.ir/hvod/2020/8/d36a2e0d-7fb9-4539-88a1-e5f27b44d7b5/v_270.mp4/seg-9-v1-a1.ts?x=gwATB_KR2oSzWKB0k7uPUzrqCCCYOZ-IwOr04H0wxQG_yfVAFrLvaI6vVi2hFQu-iOy-E2fb6S_QiWWoANRIg8o0jmVyXcwCfAOj8T7Dcn8KQpRSijm4e8Pt0d4z-gplKJuP03aroKTqeMdRY7HLCb306SPkRy4a9Dm_ixY0XTA1' for reading
[hls @ 000001babf1bd8c0] Error when loading first segment 'https://media.namava.ir/hvod/2020/8/d36a2e0d-7fb9-4539-88a1-e5f27b44d7b5/v_270.mp4/seg-1-v1-a1.ts?x=gwATB_KR2oSzWKB0k7uPUzrqCCCYOZ-IwOr04H0wxQG_yfVAFrLvaI6vVi2hFQu-iOy-E2fb6S_QiWWoANRIg8o0jmVyXcwCfAOj8T7Dcn8KQpRSijm4e8Pt0d4z-gplKJuP03aroKTqeMdRY7HLCb306SPkRy4a9Dm_ixY0XTA1'
https://media.namava.ir/hvod/2020/8/d36a2e0d-7fb9-4539-88a1-e5f27b44d7b5/v_270.mp4/index-v1-a1.m3u8?x=gwATB_KR2oSzWKB0k7uPUzrqCCCYOZ-IwOr04H0wxQG_yfVAFrLvaI6vVi2hFQu-iOy-E2fb6S_QiWWoANRIg8o0jmVyXcwCfAOj8T7Dcn8KQpRSijm4e8Pt0d4z-gplKJuP03aroKTqeMdRY7HLCb306SPkRy4a9Dm_ixY0XTA1: Invalid data found when processing input

**Comment by Dark69Sea** [comment]
منم همین مشکل داشتم 
یه راهنمایی دقیق میکنی چجوری رف کردی 403 رو

**Comment by Dark69Sea** [comment]
من با کامند اصلا باز نمیشه

**Comment by FreeMan1359** [comment]
> منم همین مشکل داشتم
> یه راهنمایی دقیق میکنی چجوری رف کردی 403 رو

سلام
ببخشید دیر به میلم سر زدم
اول بگم که فعلا این برنامه کار نمیکنه
من با خودشون هم صحبت کردم گفتن فعلا وقت ندارن که درستش کنن ولی قرار شد اگه اصلاح بشه خبر بدن
ولی در مور مشکل: من با بروزر میرفتم که این مشکل داشتم (ارور 403) و
وقتی با دستور کامند رفتم درست شد
فقط یه مورد هست که باید رعایت کنی که باید به 
 Environment Variable
مسیر بدی تا کدها در دستور کامند فعال بشن
https://john-dugan.com/add-php-windows-path-variable/

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر.

همونطور که اشاره هم کردید و در راهنمای صفحه اول برنامه نوشته شده، برنامه فقط در خط فرمان کار میکند (cmd ویندوز یا bash لینوکس) و برای مروگر طراحی نشده است.

مشکل عدم دانلود هم که اشاره شد مربوط به ورژن ffmpeg بوده که در این پست کامل توضیح دادم و حل شده است:

https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

در صورتی که مشکل شما حل نشده بود، جزئیات فنی بیشتری قرار دهید تا بررسی شود.
