### ISSUE TITLE
نمونه دستور جهت توقف دانلود

### ISSUE THREAD

**Issue by ahadzadeh** [NabiKAZ/namava-downloader#65]
با سلام
اگر امکان داره یک مثال برای توقف فایل بزنید
من متوجه اون متنی که توضیح دادین نشدم.
با تشکر

**Comment by NabiKAZ** [comment]
<div dir=rtl>

اگر اون دستورات در خط فرمان براتون سخت بود و در ویندوز هستید، task manager رو باز کنید و در لیست پروسس ها ffmpeg رو پیدا و end task کنید.

**Comment by ahadzadeh** [comment]
با سلام و تشکر
منظور من توقف دانلود یک فیلم هست
مثلا 3 فیلم در صف قرار داره من میخوام یکیشون لغو بشه

**Comment by NabiKAZ** [comment]
@ahadzadeh چک کنید فکر میکنم وقتی لیست پروسه ها میاد، اسم فایل یا مولفه دیگری که مرتبط با اون فیلم باشه دیده بشه و اینطور تشخیص بدید پروسه مرتبط با کدوم فیلمه و همونو کیل کنید.
