### ISSUE TITLE
دانلود نکردن ویدئو

### ISSUE THREAD

**Issue by majid1919** [NabiKAZ/namava-downloader#66]
سلام و عرض ادب
 من امروز چک کردم . لاگین میکنه تا مرحله آخر هم میره ولی موقع دانلود فقط فایل عکس و لاگ و اینفو رو دانلود میکنه و ویدئو رو دانلود نمیکنه
ممنون میشم بررسی کنید

**Comment by AlirezaShiri78** [comment]
سلام وقت بخیر برای دانلود از سایت های دیگه برنامه ای دارید ؟ مثل فیلم گردی ، تماشاخونه یا ...
اگه سفارش داشته باشیم انجام می دید ؟

**Comment by NabiKAZ** [comment]
> سلام و عرض ادب
> من امروز چک کردم . لاگین میکنه تا مرحله آخر هم میره ولی موقع دانلود فقط فایل عکس و لاگ و اینفو رو دانلود میکنه و ویدئو رو دانلود نمیکنه
> ممنون میشم بررسی کنید

<div dir=rtl>

چه پیامی دریافت میکنید؟
چند خط آخر لاگ فایل چیست؟

**Comment by NabiKAZ** [comment]
> سلام وقت بخیر برای دانلود از سایت های دیگه برنامه ای دارید ؟ مثل فیلم گردی ، تماشاخونه یا ...
> اگه سفارش داشته باشیم انجام می دید ؟

<div dir=rtl>

توی ذهنم هست که ارتقا پیدا کنه ولی زمانبندی خاصی ندارم.
برای پروژه هم میتونید تلگرام پیام بدید @nabikaz
برای هر موضوعی جدید هم لطفاْ تیکت جدید باز کنید.
