### ISSUE TITLE
عدم دانلود ویدئو

### ISSUE THREAD

**Issue by sheikhani** [NabiKAZ/namava-downloader#67]
ویدئو دانلود نمی‌شه و در صفحه‌ی stats.php ارور زیر دیده می‌شه.

Fatal error: Uncaught DivisionByZeroError: Division by zero in D:\Software\namava-downloader\stats.php:196 Stack trace: #0 {main} thrown in D:\Software\namava-downloader\stats.php on line 196

**Comment by NabiKAZ** [comment]
<div dir=rtl>
stats.php خیلی مهم نیست.

موقع دانلود چه خطایی میگیرید؟

**Comment by sheikhani** [comment]
خطایی نمی‌ده ولی دانلودم نمی‌شه.

**Comment by NabiKAZ** [comment]
<div dir=rtl>
چند خط آخر فایل log مربوطه رو بزارید.

**Comment by sheikhani** [comment]
کل فایل لاگ پیوست شد:
[68998_1852421.log](https://github.com/NabiKAZ/namava-downloader/files/5909249/68998_1852421.log)

خط آخر فکر کنم بخاطر بستن برنامه توسط من باشه.

**Comment by NabiKAZ** [comment]
<div dir=rtl>
اینجا رو چک کنید:

https://github.com/NabiKAZ/namava-downloader/issues/43#issuecomment-730678350

**Comment by sheikhani** [comment]
چه عجیب. ممنون بابت جواب.
