### ISSUE TITLE
پیدا نکردن فیلم

### ISSUE THREAD

**Issue by madaraacerman** [NabiKAZ/namava-downloader#70]
سلام من هر چی میزنم فیلم رو پیدا نمیکنه
![image](https://user-images.githubusercontent.com/91227021/147545583-ecfc058f-a3b5-42d3-b5fd-18132ffdd017.png)
ولی اگه میشد اینو با پایتون مینوشتین خیلی بهتره بود با پی اچ پی یکم کار سخته کلی زور زدم تا تونستم بیارمش بالا

**Comment by NabiKAZ** [comment]
من هیچ مشکلی مشاهده نکردم:
![image](https://user-images.githubusercontent.com/246721/147889282-5c8f44e0-c35c-4bf7-9986-8506faebc871.png)
لطفاً ابتدا مطمئن شوید آخرین نسخه را دانلود و استفاده میکنید و چنانچه مشکل باقی بود، خروجی این دستورات رو بفرمائید:
php -v
php -m
ffmpeg -version

پ.ن: در ضمن خوب یا بد بودن یک زبان ارتباطی به سطح دانش شما ندارد، اگر با PHP آشنایی مختصری هم داشته باشید اجرای کدها بسیار ساده است. 😉

**Comment by madaraacerman** [comment]
okeye mamnon❤️
