### ISSUE TITLE
نتونستم باهاش کار کنم

### ISSUE THREAD

**Issue by sirallix** [NabiKAZ/namava-downloader#71]
من معلوماتم در شاخه پی اچ پی و زبان های برنامه نویسی، صفره و هیچی بلد نیستم
فقط موفق شدم از نصب 2 تا نرم افزار پیشنیاز مطمئن شم
و دیگه نمیتونم فایل شمارو باز کنم
خیلی سرچ کردم اما هیچ کاری نتونستم بکنم
میتونی زیر دیپلمی هم یاد بدی یا یه ویدئو قدم به قدم درست کنی؟
یا حتی هیچی از رفع ارور ماژول که نفهمیدم

**Comment by NabiKAZ** [comment]
سلام،
همین که نیازمندی‌های نرم افزار رو تونستید نصب کنید یعنی صفر هم نیستید (:
راهنمای اجرا رو در صفحه اصلی پروژه نوشتم.
طبق همون جلو برو اگر قسمت خاصیش رو متوجه نشدی میتونی بپرسی اینجا.
