### ISSUE TITLE
کار نمی کند

### ISSUE THREAD

**Issue by simin-salari** [NabiKAZ/namava-downloader#72]
سلام 

به نظر میرسه این برنامه در حال حاضر کار نمی کند. در tasklist مقدار  | ffmpeg به سرعت نا پدید میشود.

**Comment by simin-salari** [comment]
سلام

به نظر میرسه این برنامه در حال حاضر کار نمی کند. در tasklist مقدار | ffmpeg به سرعت نا پدید میشود.

@NabiKAZ

**Comment by NabiKAZ** [comment]
باید بیکار بشم چک کنم.

**Comment by MRSheikh** [comment]
سلام 
خروجی این خطا رو میده
`= Namava Downloader - version 1.0.0 - Copyright 2020
= By Seyyed AMir <www.dblog.ir> <seyyed.a@gmail.com>
= SignUp here: https://www.namava.ir/
= Project link: https://github.com/seyyed-amir/namava-downloader
Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Desktop\namava-downloader-master\src\FilmDownloader.class.php:249
Stack trace:
#0 C:\Users\Administrator\Desktop\namava-downloader-master\src\Namava.class.php(36): FilmDownloader->getContents('https://www.nam...')
#1 C:\Users\Administrator\Desktop\namava-downloader-master\src\Namava.class.php(10): Namava->isLogin()
#2 C:\Users\Administrator\Desktop\namava-downloader-master\namava.php(56): Namava->login()
#3 {main}
  thrown in C:\Users\Administrator\Desktop\namava-downloader-master\src\FilmDownloader.class.php on line 249`

**Comment by NabiKAZ** [comment]
این راهنما رو دنبال کنید:
https://github.com/NabiKAZ/filimo-downloader/issues/55
