### ISSUE TITLE
نصب PHP

### ISSUE THREAD

**Issue by MAMSEIN** [NabiKAZ/namava-downloader#8]
با سلام
بنده توی نصب پی اچ پی در ویندوز مشکل دارم هرکاری میکنم نمیتونم نصب کنم.
میشه از طریق تلگرام در تماس باشیم؟
ممنون
آی دی من
@MAMSEIN

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سلام،
شما برای ویندوز میتونید پکیج [wamp](http://www.wampserver.com) رو نصب کنید.
