### ISSUE TITLE
پیام ارور

### ISSUE THREAD

**Issue by salam-mahdinasiri** [NabiKAZ/namava-downloader#9]
سلام
برای من این ارور رو میده
از نسخه آخر پی‌اچ‌پی استفاده می‌کنم

Deprecated: Function create_function() is deprecated in ...\stats.php on line 130

**Comment by NabiKAZ** [comment]
<div dir=rtl>

لطفاً دوباره تست کنید، مشکل باید حل شده باشد.

اگر بازهم مشکلی باقی بود لطفاً اطلاع دهید.

**Comment by majid1919** [comment]
سلام
جدیدا برای من این ارور رو میده

Logging...
PHP Notice:  Undefined offset: 1 in C:\Users\namava-downloader-master\namava-downloader-master\download.php on line 27
Logged In.
IMPORTANT: Your private cookies is stored in the 'config/' directory, Be careful about its security!
تا دوهفته پیش درست کار می کرد

**Comment by imani58ir** [comment]
سلام...منم امروز همین مشکل رو پیدا کردم...یوزر نیم پسورد ناماوا رو میزنم
وارد نمیشه این ارور میاد

**Comment by NabiKAZ** [comment]
@majid1919 @imani58ir 
https://github.com/NabiKAZ/namava-downloader/issues/16
